MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Models/Siniflar/Urun.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class Urun
    {
        [Key]
        public int UrunId { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string UrunAd { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string UrunMarka { get; set; }

        public short UrunStok { get; set; }
        public decimal UrunAlisFiyatı { get; set; }
        public decimal UrunSatisFiyatı { get; set; }
        //Kategori 
        public virtual Kategori Kategori { get; set; }
        public bool UrunDurum { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(250)]
        public string UrunFotograf { get; set; }
        //SatisHareket
        public ICollection<SatisHareket> SatisHarekets { get; set; }
    }
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;
namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class UrunController : Controller
    {
        Context db = new Context();
        // GET: Urun
        public ActionResult Index()
        {
            var urunler = db.Uruns.Where(x => x.UrunDurum == true).ToList();
            return View(urunler);
        }
        [HttpGet]
        public ActionResult UrunEkle()
        {
            
            ViewBag.allCategories = KategoriListesi(db);
            return View();
        }
        [HttpPost]
        public ActionResult UrunEkle(Urun u)
        {
            var ktg = db.Kategoris.FirstOrDefault(x => x.KategoriId == u.Kategori.KategoriId);
            u.Kategori = ktg;
            db.Uruns.Add(u);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult UrunSil(int id)
        {
            var deleted = db.Uruns.Find(id);
            deleted.UrunDurum = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult UrunGuncelle(int id)
        {
            var urun = db.Uruns.Find(id);
            ViewBag.kategoriListe = KategoriListesi(db);
            return View(urun);
        }
        [HttpPost]
        public ActionResult UrunGuncelle(Urun urun)
        {
            var urunktg = db.Kategoris.Find(urun.Kategori.KategoriId);
            var updated = db.Uruns.Find(urun.UrunId);

            updated.UrunAd = urun.UrunAd;
            updated.UrunMarka = urun.UrunMarka;
            updated.UrunStok = urun.UrunStok;
            updated.UrunAlisFiyatı = urun.UrunAlisFiyatı;
            updated.UrunSatisFiyatı = urun.UrunSatisFiyatı;
            updated.UrunFotograf = urun.UrunFotograf;
            updated.Kategori = urunktg;

            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IEnumerable<SelectListItem> KategoriListesi(Context db)
        {
            IEnumerable<SelectListItem> ktg = (from k in db.Kategoris.ToList()
                                                       select new SelectListItem
                                                       {
                                                           Text = k.KategoriAd,
                                                           Value = k.KategoriId.ToString()
                                                       }).ToList();
            return ktg;
        }
    }
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Urun/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar;
@model List<Urun>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ürün Listesi</h2>

<table class="table table-bordered">
    <tr>
        <th>Ürün Id</th>
        <th>Ürün Adı</th>
        <th>Ürün Marka</th>
        <th>Ürün Stok</th>
        <th>Ürün Alış Fiyat</th>
        <th>Ürün Satış Fiyat</th>
        <th>Ürün Fotoğraf</th>
        <th>Ürün Kategori</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var urun in Model)
    {
    <tr>
        <td>@urun.UrunId</td>
        <td>@urun.UrunAd</td>
        <td>@urun.UrunMarka</td>
        <td>@urun.UrunStok</td>
        <td>@urun.UrunAlisFiyatı</td>
        <td>@urun.UrunSatisFiyatı</td>
        <td><a class="btn btn-dark" href="@urun.UrunFotograf">Görüntüle</a></td>
        <td>@urun.Kategori.KategoriAd</td>
        <td><a class="btn btn-danger" href="/Urun/UrunSil/@urun.UrunId">Sil</a></td>
        <td><a class="btn btn-primary" href="/Urun/UrunGuncelle/@urun.UrunId">Güncelle</a></td>
    </tr>
    }
</table>
<a class="btn btn-primary" href="/Urun/UrunEkle">Yeni Urun</a>

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Urun/UrunEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Urun
@{
    ViewBag.Title = "UrunEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Yeni Ürün </h2>

<form class="form-group" action="/Urun/UrunEkle" method="post">
    <div class="form-group">
        @Html.Label("Urun Ad", new { @class = "font-bold" })
        @Html.TextBoxFor(x => x.UrunAd, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Urun Marka", new { @class = "font-bold" })
        @Html.TextBoxFor(x => x.UrunMarka, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Urun Stok Miktarı", new { @class = "font-bold" })
        @Html.TextBoxFor(x => x.UrunStok, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Urun Alış Fiyatı", new { @class = "font-bold" })
        @Html.TextBoxFor(x => x.UrunAlisFiyatı, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Urun Satış Fiyatı", new { @class = "font-bold" })
        @Html.TextBoxFor(x => x.UrunSatisFiyatı, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Urun Fotoğraf Adresi", new { @class = "font-bold" })
        @Html.TextBoxFor(x => x.UrunFotograf, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Öğrenci Kulüp");
        @Html.DropDownListFor(x =>x.Kategori.KategoriId,(List<SelectListItem>)ViewBag.allCategories,new {@class = "form-control"})
    </div>
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Urun/UrunGuncelle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Urun
@{
    ViewBag.Title = "UrunGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ürün Güncelleme Sayfası</h2>
<br />
@using (@Html.BeginForm("UrunGuncelle", "Urun", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.UrunId)
    </div>
    <div class="form-group">
        @Html.Label("Ürün Ad")
        @Html.TextBoxFor(x => x.UrunAd, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Ürün Marka")
        @Html.TextBoxFor(x => x.UrunMarka, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Ürün Stok")
        @Html.TextBoxFor(x => x.UrunStok, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Ürün Alış Fiyatı")
        @Html.TextBoxFor(x => x.UrunAlisFiyatı, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Ürün Satış Fiyatı")
        @Html.TextBoxFor(x => x.UrunSatisFiyatı, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Ürün Fotoğraf")
        @Html.TextBoxFor(x => x.UrunFotograf, new { @class = "form-control" })
    </div>
    <div>
        @Html.Label("Ürün Kategori")
        @Html.DropDownListFor(x => x.Kategori.KategoriId, (List<SelectListItem>)ViewBag.KategoriListe, new { @class = "form-control" })
    </div>
    <br />
    <button class="btn btn-info">Güncelle</button>
}