MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;
namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class MusteriController : Controller
    {
        Context db = new Context();
        // GET: Musteri
        public ActionResult Index()
        {
            var musteris = db.Musterilers.Where(x => x.Durum ==true).ToList();
            return View(musteris);
        }
        [HttpGet]
        public ActionResult MusteriEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult MusteriEkle(Musteriler m)
        {
            m.Durum = true;
            db.Musterilers.Add(m);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MusteriSil(int id)
        {
            var deleted = db.Musterilers.Find(id);
            deleted.Durum = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MusteriGuncelle(int id)
        {
            var musteriler = db.Musterilers.Find(id);
            return View(musteriler);
        }
        [HttpPost]
        public ActionResult MusteriGuncelle(Musteriler mus)
        {
            if (!ModelState.IsValid)
            {
                return View("MusteriGuncelle");
            }
            var updateMusteri= db.Musterilers.Find(mus.MusteriId);

            updateMusteri.MusteriAd = mus.MusteriAd;
            updateMusteri.MusteriSoyad = mus.MusteriSoyad;
            updateMusteri.MusteriSehir = mus.MusteriSehir;
            updateMusteri.MusteriEmail = mus.MusteriEmail;

            db.SaveChanges(); 
            return RedirectToAction("Index");
        }
        public ActionResult MusteriDetay(int id)
        {
            var degerler = db.SatisHarekets.Where(x => x.Musteriler.MusteriId == id).ToList();
            var musteriAdSoyad = db.Musterilers.Where(x => x.MusteriId == id).Select(y => y.MusteriAd +" "+y.MusteriSoyad).FirstOrDefault();
            ViewBag.musteriAdSoyad = musteriAdSoyad;
            return View(degerler);
        }
    }
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Musteri/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Musteriler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Müşteri Listesi</h2>

<table class="table table-bordered">
    <tr>
        <th>Musteri Id</th>
        <th>Müşteri Ad Soyad</th>
        <th>Müşteri Şehir</th>
        <th>Müşteri E-Mail</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var musteri in Model)
    {
<tr>
    <td>@musteri.MusteriId</td>
    <td>@musteri.MusteriAd @musteri.MusteriSoyad</td>
    <td>@musteri.MusteriSehir</td>
    <td>@musteri.MusteriEmail</td>
    <td class="text-center mx-auto widthbtn"><a class="btn btn-danger w-75" href="/Musteri/MusteriSil/@musteri.MusteriId">Sil</a></td>
    <td class="text-center mx-auto widthbtn"><a class="btn btn-primary w-75" href="/Musteri/MusteriGuncelle/@musteri.MusteriId">Güncelle</a></td>
    <td class="text-center mx-auto widthbtn"><a class="btn btn-dark w-75" href="/Musteri/MusteriDetay/@musteri.MusteriId">Detaylar</a></td>
</tr>
    }
</table>
<a class="btn btn-primary" href="/Musteri/MusteriEkle">Yeni Müşteri Ekle</a>

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Musteri/MusteriDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "MusteriSatis";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h2>Müşteri Satis Bilgi Ekranı</h2>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active text-dark">Müşteri Adı : <strong>@ViewBag.musteriAdSoyad</strong></li>
</ol>
<br />

<table class="table table-condensed">
    <tr>
        <th>
            Satış Id
        </th>
        <th>
            Ürün
        </th>
        <th>
            Adet
        </th>
        <th>
            Fiyat
        </th>
        <th>
            Toplam Tutar
        </th>
        <th>
            Satışı Yapan Personel
        </th>
        <th>
            Satış Tarihi
        </th>
        <th>
            Yazdır
        </th>
    </tr>
    @foreach (var satis in Model)
    {
<tr>
    <td>@satis.SatisId</td>
    <td>@satis.Urun.UrunAd</td>
    <td>@satis.Adet</td>
    <td>@satis.Fiyat</td>
    <td>@satis.ToplamTutar</td>
    <td><a href="/Departman/DepartmanPersonelSatisBilgi/@satis.Personel.PersonelId">@satis.Personel.PersonelAd @satis.Personel.PersonelSoyad</a></td>
    <td>@satis.SatisTarih.ToString()</td>
    <td><a class="btn btn-light btn-outline-dark" href="#">Yazdır</a></td>
</tr>
    }
</table>

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Musteri/MusteriEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Musteriler
@{
    ViewBag.Title = "MusteriEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Müşteri Ekle</h2>

<form class="form-group" action="/Musteri/MusteriEkle" method="post">
    @Html.Label("Müşteri Ad", new { @class = "font-bold" })
    @Html.TextBoxFor(x => x.MusteriAd, new { @class = "form-control" })
    <br />
    @Html.Label("Müşteri Soyad", new { @class = "font-bold" })
    @Html.TextBoxFor(x => x.MusteriSoyad, new { @class = "form-control" })
    <br />
    @Html.Label("Müşteri Şehir", new { @class = "font-bold" })
    @Html.TextBoxFor(x => x.MusteriSehir, new { @class = "form-control" })
    <br />
    @Html.Label("Müşteri E-Mail", new { @class = "font-bold" })
    @Html.TextBoxFor(x => x.MusteriEmail, new { @class = "form-control"})
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Musteri/MusteriGuncelle.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model Musteriler
@{
    ViewBag.Title = "MusteriGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Müşteri Güncelleme Ekranı</h2>
<br />
@using (Html.BeginForm("MusteriGuncelle", "Musteri", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.MusteriId)

    @Html.Label("Müşteri Ad")
    @Html.TextBoxFor(x => x.MusteriAd, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.MusteriAd, "", new { @style = "color : red;" })
    <br />
    @Html.Label("Müşteri Soyad")
    @Html.TextBoxFor(x => x.MusteriSoyad, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.MusteriSoyad, "", new { @style = "color : red;" })
    <br />
    @Html.Label("Müşteri Şehir")
    @Html.TextBoxFor(x => x.MusteriSehir, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.MusteriSehir, "", new { @style = "color : red;" })
    <br />
    @Html.Label("Müşteri E-Mail")
    @Html.TextBoxFor(x => x.MusteriEmail, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.MusteriEmail, "", new { @style = "color : red;" })
</div>
    <button class="btn btn-info">Güncelle</button>
}