MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Models/Siniflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class Departman
    {
        [Key]
        public int DepartmentId { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string DepartmentAd { get; set; }
        public bool Durum { get; set; }
        public ICollection<Personel> Personels { get; set; }

    }
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;
namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class DepartmanController : Controller
    {
        Context db = new Context();
        // GET: Departman
        public ActionResult Index()
        {
            var departmans = db.Departmans.Where(x => x.Durum == true).ToList();
            return View(departmans);
        }
        [HttpGet]
        public ActionResult DepartmanEkle()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DepartmanSil(int id)
        {
            var deleted = db.Departmans.Find(id);
            deleted.Durum = false;
            db.SaveChanges();   
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult DepartmanEkle(Departman d)
        {
            db.Departmans.Add(d);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult DepartmanDetay(int id)
        {
            var departmanbilgi = db.Departmans.Find(id);
            var personeller = db.Personels.Where(x => x.Departman.DepartmentId == id).ToList();
            var departmanAd = db.Departmans.Where(x => x.DepartmentId == id).Select(y => y.DepartmentAd).FirstOrDefault();
            ViewBag.depAd = departmanAd;
            return View(personeller);
        }
        public ActionResult DepartmanGuncelle(int id)
        {
            var departman = db.Departmans.Find(id);
            return View(departman);
        }
        [HttpPost]
        public ActionResult DepartmanGuncelle(Departman dep)
        {
            var updateDepartman = db.Departmans.Find(dep.DepartmentId);
            updateDepartman.DepartmentAd = dep.DepartmentAd;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanPersonelSatisBilgi(int id)
        {
            var satislar = db.SatisHarekets.Where(x => x.Personel.PersonelId == id).ToList();
            var personelAd = db.Personels.Where(x => x.PersonelId == id).Select(y => y.PersonelAd + " " + y.PersonelSoyad).FirstOrDefault();
            ViewBag.personelAd = personelAd;
            return View(satislar);
        }
    }
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Departman/DepartmanDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar;
@model List<Personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h2>Departman Personel Listesi</h2>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active text-dark">Departman Adı : <strong>@ViewBag.depAd</strong></li>
</ol>
<br />

<table class="table table-bordered">
    <tr>
        <th>
            Personel Id
        </th>
        <th>
            Personel Ad
        </th>
        <th>
            Personel Soyad
        </th>
        <th>
            Personel Fotoğraf
        </th>
        <th>
            Personele Ait Satışlar
        </th>
    </tr>
    @foreach (var personel in Model)
    {
        <tr>
            <td class="text-center">@personel.PersonelId</td>
            <td class="text-center">@personel.PersonelAd</td>
            <td class="text-center">@personel.PersonelSoyad</td>
            <td class="text-center"><a class="btn btn-danger" href="@personel.PersonelFotograf">Fotoğraf</a></td>
            <td class="text-center"><a href="/Departman/DepartmanPersonelSatisBilgi/@personel.PersonelId" class="btn btn-danger">Satışlar</a></td>
        </tr>
    }
</table>

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Departman/DepartmanEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Departman Ekleme Sayfası</h2>
<br />
<form class="form-group" action="/Departman/DepartmanEkle" method="post">
    @Html.Label("Departman Ad", new { @class = "font-bold" })
    @Html.TextBoxFor(x => x.DepartmentAd, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Departman/DepartmanGuncelle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Departman Güncelle</h2>
<br />
@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.DepartmentId)
        @Html.Label("Departman Ad")
        @Html.TextBoxFor(x => x.DepartmentAd, new { @class = "form-control" })
    </div>
    <button class="btn btn-info">Güncelle</button>
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Departman/DepartmanPersonelSatisBilgi.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "DepartmanPersonelSatisBilgi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h2>Personel Satış Bilgi Sayfası</h2>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active text-dark">Personel Adı : <strong>@ViewBag.personelAd</strong></li>
</ol>
<br />
<table class="table table-condensed">
    <tr>
        <th>Satış Id</th>
        <th>Ürün Adı</th>
        <th>Müşteri Adı</th>
        <th>Adet</th>
        <th>Fiyat</th>
        <th>Toplam Tutar</th>
        <th>Satış Tarihi</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var satislar in Model)
    {
        <tr>
            <td>@satislar.SatisId</td>
            <td>@satislar.Urun.UrunAd</td>
            <td>@satislar.Musteriler.MusteriAd @satislar.Musteriler.MusteriSoyad</td>
            <td>@satislar.Adet</td>
            <td>@satislar.Fiyat</td>
            <td>@satislar.ToplamTutar</td>
            <td>@satislar.SatisTarih.ToString()</td>
            <td><a class="btn btn-light btn-outline-dark" href="#">Yazdır</a></td>
        </tr>
    }
</table>

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Departman/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Departman Listesi</h2>


<table class="table table-bordered">
    <tr>
        <th class="w-25">Departman Id</th>
        <th>Departman Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var departman in Model)
    {
    <tr>
        <td>@departman.DepartmentId</td>
        <td>@departman.DepartmentAd</td>
        <td class="text-center mx-auto widthbtn"><a class="btn btn-danger w-75" href="/Departman/DepartmanSil/@departman.DepartmentId">Sil</a></td>
        <td class="text-center mx-auto widthbtn"><a class="btn btn-primary w-75"href="/Departman/DepartmanGuncelle/@departman.DepartmentId">Güncelle</a></td>
        <td class="text-center mx-auto widthbtn"><a class="btn btn-dark w-75" href="/Departman/DepartmanDetay/@departman.DepartmentId">Detaylar</a></td>
    </tr>
    }
</table>
<a class="btn btn-primary" href="/Departman/DepartmanEkle">Yeni Departman</a>