MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Models/Siniflar/Kategori.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class Kategori
    {
        [Key]
        public int KategoriId { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string KategoriAd { get; set; }
        public ICollection<Urun> Uruns { get; set; }
    }
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;
namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class KategoriController : Controller
    {
        Context db = new Context();
        // GET: Kategori
        public ActionResult Index()
        {
            var kategoriler = db.Kategoris.ToList();
            return View(kategoriler);
        }
        [HttpGet]
        public ActionResult KategoriEkle()
        {
           return View();
        }
        [HttpPost]
        public ActionResult KategoriEkle(Kategori k)
        {
            db.Kategoris.Add(k);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult KategoriSil(int id)
        {
            var deleted = db.Kategoris.Find(id);
            db.Kategoris.Remove(deleted);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult KategoriGuncelle(int id)
        {
            var updated = db.Kategoris.Find(id);
            return View(updated);
        }
        [HttpPost]
        public ActionResult KategoriGuncelle(Kategori k)
        {
            var updated = db.Kategoris.Find(k.KategoriId);
            updated.KategoriAd = k.KategoriAd;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Kategori/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar;
@model List<Kategori>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kategori Listesi</h2>

<table class="table table-bordered">
    <tr>
        <th class="w-25">Kategori Id</th>
        <th>Kategori Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach(var kategori in Model) { 
    <tr>
        <td>@kategori.KategoriId</td>
        <td>@kategori.KategoriAd</td>
        <td><a class="btn btn-danger" href="/Kategori/KategoriSil/@kategori.KategoriId">Sil</a></td>
        <td><a class="btn btn-primary" href="/Kategori/KategoriGuncelle/@kategori.KategoriId">Güncelle</a></td>
    </tr>
    }
</table>
<a class="btn btn-primary" href="/Departman/DepartmanEkle">Yeni Departman</a>

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Kategori/KategoriEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Kategori
@{
    ViewBag.Title = "KategoriEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h2>Kategori Ekle Sayfası</h2>
<br />
<form class="form-group" action="/Kategori/KategoriEkle" method="post">
    @Html.Label("Kategori Ad",new { @class = "font-bold" })
    @Html.TextBoxFor(x=>x.KategoriAd,new { @class = "form-control"})
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Kategori/KategoriGuncelle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Kategori
@{
    ViewBag.Title = "KategoriGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kategori Güncelle</h2>
<br />
@using (@Html.BeginForm("KategoriGuncelle", "Kategori", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.KategoriId)
        @Html.Label("Kategori Ad")
        @Html.TextBoxFor(x => x.KategoriAd, new { @class = "form-control" })
    </div>
    <button class="btn btn-info">Güncelle</button>
}